version: '3.7'
services:
  zatech-backend:
    build:
      context: .
    ports:
      - 8443:8080
    environment:
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=password
    networks:
      zatech:
        aliases:
          - zatech-backend

networks:
  zatech:
    name: zatech
